version: "3"

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db.dockerfile
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web.dockerfile
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
